DROP TABLE IF EXISTS url_checks;
DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255),
  created_at TIMESTAMP 
  );

CREATE TABLE url_checks (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  url_id bigint REFERENCES urls (id),
  status_code VARCHAR(255),
  h1 VARCHAR(255),
  title VARCHAR(255),
  content VARCHAR(255),
  created_at TIMESTAMP
  );
